name: build
on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
          cache: "pip"

      - name: Install bsdtar
        run: sudo apt-get update && sudo apt-get install -y libarchive-tools

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install struct-eqtable
        env:
          TARGET: ./doc_page_extractor/struct_eqtable
          TAG: v0.3.0.1
        run: |
          if [ -d "$TARGET" ]; then
            rm -rf "$TARGET"
          fi
          mkdir -p $TARGET
          curl -sL "https://github.com/Moskize91/StructEqTable/releases/download/$TAG/struct_eqtable.zip" | bsdtar -xzf - -C "$TARGET"

      - name: Lint
        run: |
          pip install pylint==3.3.4
          pylint --generated-member=cv2 ./**/*.py

      # TODO: Github Action cannot run AI
      # - name: Run unit tests
      #   run: python test.py