name: build
on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install struct-eqtable
        run: |
          if [ -d "./struct_eqtable" ]; then
            rm -rf "./struct_eqtable"
          fi
          mkdir -p ./struct_eqtable
          curl -sL "https://github.com/Moskize91/StructEqTable/releases/download/v0.3.0.1/struct_eqtable.zip" | tar -xz -C ./struct_eqtable

      - name: Lint
        run: |
          pip install pylint==3.3.4
          pylint --generated-member=cv2 ./**/*.py

      # TODO: Github Action cannot run AI
      # - name: Run unit tests
      #   run: python test.py